server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: todo-route
          uri: http://todo-service:8082
          predicates:
            - Path=/**
            - Header=Authorization, .*
#            - Method=GET
  sleuth:
    enabled: true
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true